StatTracker/Models/Game.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using Newtonsoft.Json;

namespace StatTracker.Models
{
    public class Game
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string StatsString { get; set; }
        public Dictionary<string, float> Stats
        {
            get
            {
                return JsonConvert.DeserializeObject<Dictionary<string, float>>(StatsString);
            }
            set
            {
                StatsString = JsonConvert.SerializeObject(value);
            }
        }
    }
}

StatTracker/Models/Player.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using Newtonsoft.Json;

namespace StatTracker.Models
{
    public class Player
    {
        public int Id { get; set; }
        public string Name { get; set; }

        public Game Game { get; set; }
        public int GameId { get; set; }
        public string StatsString { get; set; }
        public Dictionary<string, float> Stats
        {
            get
            {
                return JsonConvert.DeserializeObject<Dictionary<string, float>>(StatsString);
            }
            set
            {
                StatsString = JsonConvert.SerializeObject(value);
            }
        }
    }
}

StatTracker/Models/StatTrackerContext.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

using System.Data.Entity;

namespace StatTracker.Models
{
    public class StatTrackerContext : DbContext
    {

        public StatTrackerContext()

        {

        }

        //Entities

        public DbSet<Game> Games { get; set; }

        public DbSet<Player> Players { get; set; }
    }
}

StatTracker/Controllers/GamesController.cs
using System;
using System.Collections.Generic;
using System.Collections.Specialized;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using StatTracker.Models;

namespace StatTracker.Controllers
{
    public class GamesController : Controller
    {
        private StatTrackerContext db = new StatTrackerContext();

        // GET: Games
        public ActionResult Index()
        {
            return View(db.Games.ToList());
        }

        // GET: Games/Stats/5
        public ActionResult Stats(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Game game = db.Games.Find(id);
            if (game == null)
            {
                return HttpNotFound();
            }
            return View(game);
        }

        // GET: Games/Stats/5
        public ActionResult Players(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
           
            IEnumerable<Player> players = db.Players.Where(x => x.GameId == id).ToList();
            return View(players);
        }

        // GET: Games/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Games/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Name")] Game game)
        {
            if (ModelState.IsValid)
            {
                db.Games.Add(game);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(game);
        }

        // GET: Games/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Game game = db.Games.Find(id);
            if (game == null)
            {
                return HttpNotFound();
            }
            return View(game);
        }

        // POST: Games/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Name")] Game game)
        {
            if (ModelState.IsValid)
            {
                db.Entry(game).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(game);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditStats([Bind(Include = "Id,Name")] Game game)
        {
            string[] stats = Request.Form["stats"].Split(',');
            Dictionary<string, float> newStatsDictionary = new Dictionary<string, float>();
            foreach (string stat in stats)
            {
                if (stat.Length > 0 && !newStatsDictionary.ContainsKey(stat))
                    newStatsDictionary.Add(stat, 0);
            }

            Game gameInDb = db.Games.Find(game.Id);
            gameInDb.Stats = newStatsDictionary;
            db.SaveChanges();

            return RedirectToAction("Index");
        }

        // GET: Games/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Game game = db.Games.Find(id);
            if (game == null)
            {
                return HttpNotFound();
            }
            return View(game);
        }

        // POST: Games/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Game game = db.Games.Find(id);
            db.Games.Remove(game);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

StatTracker/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace StatTracker.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

StatTracker/Views/Games/Create.cshtml
@model StatTracker.Models.Game

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Game</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

StatTracker/Views/Games/Delete.cshtml
@model StatTracker.Models.Game

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Game</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

StatTracker/Views/Games/Details - Copy.cshtml
@model StatTracker.Models.Game

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>@Model.Name</h4>
    <hr />
</div>
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4>Stats</h4>

    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.Id)

    <table class="table table-bordered table-hover">
        <thead>
            <tr>
                <th>Stat Name</th>
                <th>Value</th>
            </tr>
        </thead>
        <tbody>
            @if (Model.Stats != null)
            {
            foreach (KeyValuePair<string, float> entry in Model.Stats)
            {
                <tr>
                    <td>@entry.Key</td>
                    <td>@entry.Value</td>
                </tr>
            }
            }
        </tbody>
    </table>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save" class="btn btn-default" />
        </div>
    </div>
</div>
}
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

StatTracker/Views/Games/Details.cshtml
@model StatTracker.Models.Game

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>@Model.Name</h4>
    <hr />
</div>
@using (Html.BeginForm("EditStats", "Games"))
{
<div class="form-horizontal">
    <h4>Stats</h4>

    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

    <div class="form-group" id="addRowsHere">
        @if (Model.Stats == null || Model.Stats.Count == 0)
        {
            <p>No stats have been added yet.</p>
        }
        else
        {
            foreach (KeyValuePair<string, float> entry in Model.Stats)
            {
                <input type="text" class="form-control" v-model="act" name="stats" value="@entry.Key">
            }
        }






    </div>
    <input type="button" class="btn btn-default" id="more_fields" value="Add Stat" />
    @Html.HiddenFor(model => model.Id)
    @Html.AntiForgeryToken()
    <button type="submit" class="btn btn-primary">Save</button>
</div>

}
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>


<script>
    document.getElementById("more_fields").onclick = function () {
   

        //input
        var newInput = document.createElement("input");
        newInput.setAttribute("type", "text");
        newInput.setAttribute("class", "form-control");
        newInput.setAttribute("v-model", "act");
        newInput.setAttribute("name", "stats");

        var element = document.getElementById("addRowsHere");
        element.appendChild(newInput);
    };

</script>

StatTracker/Views/Games/Edit.cshtml
@model StatTracker.Models.Game

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Game</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

StatTracker/Views/Games/Index.cshtml
@model IEnumerable<StatTracker.Models.Game>

@{
    ViewBag.Title = "Index";
}

<h2>Games</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
            @Html.ActionLink("Stats", "Stats", new { id = item.Id }) |
            @Html.ActionLink("Players", "Players", new { id = item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id = item.Id })
        </td>
    </tr>
}

</table>

StatTracker/Views/Games/Players.cshtml
@model IEnumerable<StatTracker.Models.Player>

@{
    ViewBag.Title = "Players";
}

<h2>Players</h2>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th></th>
    </tr>

    @if (Model.Count() == 0)
    {
        <tr>
            <td>
                No players have been added yet.
            </td>
        </tr>
                
                }
                else
                {
                foreach (var player in Model)
                {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => player.Name)
            </td>
            <td>
                @Html.ActionLink("Stats", "Stats", new { id = player.Id }) |
                @Html.ActionLink("Delete", "Delete", new { id = player.Id })
            </td>
        </tr>
        }
        }

    </table>

StatTracker/Views/Games/Stats.cshtml
@model StatTracker.Models.Game

@{
    ViewBag.Title = "Details";
}

<h2>Stats</h2>

<div>
    <h4>@Model.Name</h4>
    <hr />
</div>
@using (Html.BeginForm("EditStats", "Games"))
{
<div class="form-horizontal">

    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

    <div class="form-group" id="addRowsHere">
        @if (Model.Stats == null || Model.Stats.Count == 0)
        {
            <p>No stats have been added yet.</p>
        }
        else
        {
            foreach (KeyValuePair<string, float> entry in Model.Stats)
            {
                <input type="text" class="form-control" v-model="act" name="stats" value="@entry.Key">
            }
        }






    </div>
    <input type="button" class="btn btn-default" id="more_fields" value="Add Stat" />
    @Html.HiddenFor(model => model.Id)
    @Html.AntiForgeryToken()
    <button type="submit" class="btn btn-primary">Save</button>
</div>

}
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>


<script>
    document.getElementById("more_fields").onclick = function () {
   

        //input
        var newInput = document.createElement("input");
        newInput.setAttribute("type", "text");
        newInput.setAttribute("class", "form-control");
        newInput.setAttribute("v-model", "act");
        newInput.setAttribute("name", "stats");

        var element = document.getElementById("addRowsHere");
        element.appendChild(newInput);
    };

</script>

StatTracker/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

StatTracker/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

StatTracker/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

StatTracker/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("Games", "Index", "Games")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>